In [4]:

import numpy as np 
import math
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression as regress
import statsmodels.formula.api as sm

import pandas as pd
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
from sklearn import cross_validation
from sklearn.linear_model import LinearRegression

In [12]:
dt = pd.read_csv("gssincome.csv")
data=dt.values.T
income=dt['income'].values
age=dt['age'].values
foreignborn=dt['foreignborn'].values
female=dt['female'].values
crack=dt['crack'].values
educ=dt['educ'].values
numchildren=dt['numchildren'].values

Y=income
X=np.vstack([age,foreignborn,female,crack,educ,numchildren])
Y.size

1379

In [6]:

pca = PCA(n_components=6)
pca.fit(X)
print(pca.explained_variance_ratio_)
print(pca.components_)



[  9.54963189e-01   4.28744682e-02   1.82324631e-03   2.47076004e-04
   9.20200233e-05   7.10738993e-31]
[[ -3.23932056e-02  -1.06328609e-02  -3.41185390e-02 ...,  -8.92354013e-03
   -1.08692734e-02  -4.53411599e-02]
 [  3.40398982e-03   4.73257505e-02  -3.30280864e-03 ...,   4.30662761e-02
    3.34829452e-02  -4.40360127e-02]
 [ -3.26519540e-02  -1.38971478e-02  -3.09446802e-03 ...,  -6.32701478e-03
   -1.54132319e-02  -1.70608556e-02]
 [ -2.13374373e-02   2.61816829e-02   2.67657473e-02 ...,  -1.94361000e-02
   -3.51111513e-02   3.28620216e-02]
 [  1.08287061e-02  -9.50585074e-04  -3.90115104e-04 ...,   9.82593006e-03
    8.24883560e-02  -3.44630483e-03]
 [  9.96136323e-01  -3.27274123e-02  -1.12253558e-02 ...,  -4.21259752e-04
   -4.05229026e-03   7.61510077e-04]]


In [7]:

np.cumsum(np.round(pca.explained_variance_ratio_, decimals=5)*100)

array([ 95.496,  99.783,  99.965,  99.99 ,  99.999,  99.999])

In [19]:
Z=X*pca.components_
#print(Z[0])
df = pd.DataFrame({"Y": Y, "Z1": Z[0], "Z2": Z[1]})
result = sm.ols(formula="Y ~ Z1", data=df).fit()
print(result.params)
Yhat = result.params[0]+result.params[1]*Z[0]
SSE = np.sum((Y - Yhat)**2)
SST = (Y.size-1)*np.var(Y)
print("SSE from first PCA Component =", SSE,"and R-sq =",1-SSE/SST)
result2 = sm.ols(formula="Y ~ Z1 + Z2", data=df).fit()
Yhat2 = result2.params[0]+result2.params[1]*Z[0]+result2.params[2]*Z[1]
SSE2 = np.sum((Y - Yhat2)**2)
print("SSE from first two PCA Components =",SSE2,"and R-sq =",1-SSE2/SST)
print(Yhat[0:4])
print(Y[0:4])

Intercept    35403.678568
Z1          -14286.081076
dtype: float64
SSE from first PCA Component = 2.78580434095e+12 and R-sq = 0.0446253661996
SSE from first two PCA Components = 2.77204468056e+12 and R-sq = 0.0493441579363
[ 52526.24111917  36922.69770219  54900.48711927  38006.33739291]
[87470 88570 13140 41050]
